server:
  port: 8777
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
            
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
 
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
 
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka